### ISSUE TITLE
release 1.0.3 준비작업

### ISSUE THREAD

**Issue by stealmh** [YAPP-Github/24th-App-Team-4-iOS#120]
## 어떤 버그인가요?
`도형` `민호`
#### 9월11일(수) ~ 9월 21일(토) (release 1.0.3)
- [x] CategorySetting으로 이동하는 시점에 Perception Tracking 경고 발생 `민호`
- [x] dismiss 시 검은화면 보이는 현상 (실제 디바이스에서 재현이 안됨 확인되면 수정)
- [x] 검색화면에서 빠르게 아래로 스크롤 시 페이징이 멈추는 현상 `도형`
- [x] 링크 수정에서 카테고리 추가하고 돌아오면 미적용 버그 `민호`
- [x] ContentList 컨텐츠 갯수 수정 `도형`
- [x] 미분류 링크 삭제 안되는 문제 수정 `도형`
- [x] CategoryDetail 페이지네이션 오류 수정 `도형`
- [ ] ContentList에 위와 똑같은 상황에서, BottomSheet가 계속 떠버리는 현상 `도형`
-> 우선순위를 고려하여 장기적인 버그 해결목록으로 이동
- [ ] ContentDetail을 내리고 빠르게 뒤로가기 제스처를 하면 앱이 멈춰버리는 현상 `도형`
-> 우선순위를 고려하여 장기적인 버그 해결목록으로 이동

## 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

**Comment by ShapeKim98** [comment]
> dismiss 시 검은화면 보이는 현상 이거 재현되나요 지금? @ShapeKim98 되면 어떤상황에서 발생하는지좀.. 저는 안나와서

그러네 갑자기 안나오네여.. 시뮬에서만 발생한 현상인가..?
