### ISSUE TITLE
Fastlane 추가

### ISSUE THREAD

**Issue by stealmh** [YAPP-Github/24th-App-Team-4-iOS#26]
## 작업사항

1. Fastlane을 통해 Pokit Private repository에서 파일을 다운로드합니다. 
2. 자동배포를 위한 기능 추가
3. 사이닝 관련 문제 해결

## 작업 상세 내용

- [x] Fastlane 추가
- [x] make 파일 수정
- [x] 팀 사이닝 레포에서의 설정값 세팅 후 다운로드

**Comment by ShapeKim98** [comment]
엇 나도 해볼려 했는데.. 한발 늦었다...

**Comment by stealmh** [comment]
> 엇 나도 해볼려 했는데.. 한발 늦었다...

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 나 하나도몰라서 공부하면서 할거라 이 이슈는 매우 롱런할예정😢 같이하시져
